calibration_dataset_dir: "/home/hwei/reesearch/datasets/web_scraping_0922_google-hybrid_medmnist_lazy-load-fix_50size"
results_store_dir: "/home/hwei/reesearch/experiments/msmarco-bert-base_0922_google-hybrid_medmnist_lazy-load-fix_sentence-splitting_50size"

class_list_csv: "/home/hwei/reesearch/zero-shot-conformal-prediction/medmnist/medmnist_classes.csv"

tokenizer:
  path: &tokenizer_path "sentence-transformers/msmarco-bert-base-dot-v5"
  kwargs: {}
query_encoder:
  path: